apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpuminer-multi 
  labels:
    app: cpuminer-multi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpuminer-multi
  template:
    metadata:
      labels:
        app: cpuminer-multi
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 1.1.1.1
          - 1.0.0.1
      nodeSelector:
        core: i7
      containers:
      - name: cpuminer-multi
        image: docker.io/wernight/cpuminer-multi
        cmd: ["cpuminer"]
        args: ["--algo=scrypt", "--url=stratum+tcp://us.litecoinpool.org:3333", "--userpass=sfxworks.1:1"]

