apiVersion: apps/v1
kind: Deployment
metadata:
  name: minergate-cli
  labels:
    app: minergate-cli
spec:
  replicas: 2
  selector:
    matchLabels:
      app: minergate-cli
  template:
    metadata:
      labels:
        app: minergate-cli
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 1.1.1.1
          - 1.0.0.1
      nodeSelector:
        core: i7
      containers:
      - name: minergate-cli
        image: ubuntu:16.04
        tty: true
        stdin: true
        volumeMounts:
        - mountPath: /root/.bitmonero
          name: bitmonero-volume
        command: ["/bin/sh", "-c"]
        args: ["apt-get update && apt-get upgrade -y &&
        apt-get install software-properties-common -y && 
        add-apt-repository ppa:ubuntu-toolchain-r/test  &&
        apt-get update &&
        apt-get install gcc-4.9 wget ocl-icd-libopencl1 -y &&
        apt-get upgrade libstdc++6 -y &&
        wget https://minergate.com/download/xfast-ubuntu-cli-amd && dpkg -i xfast-ubuntu-cli-amd && minergate-cli --user sfxworks@gmail.com --xmr"]



pull raboo/monero